<?php

namespace Sunaoka\Aws\Structures\AlexaForBusiness\GetDevice\Shapes;

use Sunaoka\Aws\Structures\Shape;

/**
 * @property 'BLUETOOTH'|'VOLUME'|'NOTIFICATIONS'|'LISTS'|'SKILLS'|'NETWORK_PROFILE'|'SETTINGS'|'ALL'|null $Feature
 * @property 'DEVICE_SOFTWARE_UPDATE_NEEDED'|'DEVICE_WAS_OFFLINE'|'CREDENTIALS_ACCESS_FAILURE'|'TLS_VERSION_MISMATCH'|'ASSOCIATION_REJECTION'|'AUTHENTICATION_FAILURE'|'DHCP_FAILURE'|'INTERNET_UNAVAILABLE'|'DNS_FAILURE'|'UNKNOWN_FAILURE'|'CERTIFICATE_ISSUING_LIMIT_EXCEEDED'|'INVALID_CERTIFICATE_AUTHORITY'|'NETWORK_PROFILE_NOT_FOUND'|'INVALID_PASSWORD_STATE'|'PASSWORD_NOT_FOUND'|'PASSWORD_MANAGER_ACCESS_DENIED'|'CERTIFICATE_AUTHORITY_ACCESS_DENIED'|null $Code
 */
class DeviceStatusDetail extends Shape
{
    /**
     * @param array{
     *     Feature?: 'BLUETOOTH'|'VOLUME'|'NOTIFICATIONS'|'LISTS'|'SKILLS'|'NETWORK_PROFILE'|'SETTINGS'|'ALL'|null,
     *     Code?: 'DEVICE_SOFTWARE_UPDATE_NEEDED'|'DEVICE_WAS_OFFLINE'|'CREDENTIALS_ACCESS_FAILURE'|'TLS_VERSION_MISMATCH'|'ASSOCIATION_REJECTION'|'AUTHENTICATION_FAILURE'|'DHCP_FAILURE'|'INTERNET_UNAVAILABLE'|'DNS_FAILURE'|'UNKNOWN_FAILURE'|'CERTIFICATE_ISSUING_LIMIT_EXCEEDED'|'INVALID_CERTIFICATE_AUTHORITY'|'NETWORK_PROFILE_NOT_FOUND'|'INVALID_PASSWORD_STATE'|'PASSWORD_NOT_FOUND'|'PASSWORD_MANAGER_ACCESS_DENIED'|'CERTIFICATE_AUTHORITY_ACCESS_DENIED'|null
     * } $args
     */
    public function __construct(array $args = [])
    {
        $this->__data = $args;
    }
}
