<?php

namespace Sunaoka\Aws\Structures\NimbleStudio\DeleteLaunchProfile\Shapes;

use Sunaoka\Aws\Structures\Shape;

/**
 * @property 'VALIDATION_NOT_STARTED'|'VALIDATION_IN_PROGRESS'|'VALIDATION_SUCCESS'|'VALIDATION_FAILED'|'VALIDATION_FAILED_INTERNAL_SERVER_ERROR' $state
 * @property 'VALIDATION_NOT_STARTED'|'VALIDATION_IN_PROGRESS'|'VALIDATION_SUCCESS'|'VALIDATION_FAILED_INVALID_SUBNET_ROUTE_TABLE_ASSOCIATION'|'VALIDATION_FAILED_SUBNET_NOT_FOUND'|'VALIDATION_FAILED_INVALID_SECURITY_GROUP_ASSOCIATION'|'VALIDATION_FAILED_INVALID_ACTIVE_DIRECTORY'|'VALIDATION_FAILED_UNAUTHORIZED'|'VALIDATION_FAILED_INTERNAL_SERVER_ERROR' $statusCode
 * @property string $statusMessage
 * @property 'VALIDATE_ACTIVE_DIRECTORY_STUDIO_COMPONENT'|'VALIDATE_SUBNET_ASSOCIATION'|'VALIDATE_NETWORK_ACL_ASSOCIATION'|'VALIDATE_SECURITY_GROUP_ASSOCIATION' $type
 */
class ValidationResult extends Shape
{
    /**
     * @param array{
     *     state: 'VALIDATION_NOT_STARTED'|'VALIDATION_IN_PROGRESS'|'VALIDATION_SUCCESS'|'VALIDATION_FAILED'|'VALIDATION_FAILED_INTERNAL_SERVER_ERROR',
     *     statusCode: 'VALIDATION_NOT_STARTED'|'VALIDATION_IN_PROGRESS'|'VALIDATION_SUCCESS'|'VALIDATION_FAILED_INVALID_SUBNET_ROUTE_TABLE_ASSOCIATION'|'VALIDATION_FAILED_SUBNET_NOT_FOUND'|'VALIDATION_FAILED_INVALID_SECURITY_GROUP_ASSOCIATION'|'VALIDATION_FAILED_INVALID_ACTIVE_DIRECTORY'|'VALIDATION_FAILED_UNAUTHORIZED'|'VALIDATION_FAILED_INTERNAL_SERVER_ERROR',
     *     statusMessage: string,
     *     type: 'VALIDATE_ACTIVE_DIRECTORY_STUDIO_COMPONENT'|'VALIDATE_SUBNET_ASSOCIATION'|'VALIDATE_NETWORK_ACL_ASSOCIATION'|'VALIDATE_SECURITY_GROUP_ASSOCIATION'
     * } $args
     */
    public function __construct(array $args)
    {
        $this->__data = $args;
    }
}
