<?php

namespace Sunaoka\Aws\Structures\MediaLive;

class MediaLiveClient extends \Aws\MediaLive\MediaLiveClient
{
    use AcceptInputDeviceTransfer\AcceptInputDeviceTransferTrait;
    use BatchDelete\BatchDeleteTrait;
    use BatchStart\BatchStartTrait;
    use BatchStop\BatchStopTrait;
    use BatchUpdateSchedule\BatchUpdateScheduleTrait;
    use CancelInputDeviceTransfer\CancelInputDeviceTransferTrait;
    use ClaimDevice\ClaimDeviceTrait;
    use CreateChannel\CreateChannelTrait;
    use CreateInput\CreateInputTrait;
    use CreateInputSecurityGroup\CreateInputSecurityGroupTrait;
    use CreateMultiplex\CreateMultiplexTrait;
    use CreateMultiplexProgram\CreateMultiplexProgramTrait;
    use CreatePartnerInput\CreatePartnerInputTrait;
    use CreateTags\CreateTagsTrait;
    use DeleteChannel\DeleteChannelTrait;
    use DeleteInput\DeleteInputTrait;
    use DeleteInputSecurityGroup\DeleteInputSecurityGroupTrait;
    use DeleteMultiplex\DeleteMultiplexTrait;
    use DeleteMultiplexProgram\DeleteMultiplexProgramTrait;
    use DeleteReservation\DeleteReservationTrait;
    use DeleteSchedule\DeleteScheduleTrait;
    use DeleteTags\DeleteTagsTrait;
    use DescribeChannel\DescribeChannelTrait;
    use DescribeInput\DescribeInputTrait;
    use DescribeInputDevice\DescribeInputDeviceTrait;
    use DescribeInputDeviceThumbnail\DescribeInputDeviceThumbnailTrait;
    use DescribeInputSecurityGroup\DescribeInputSecurityGroupTrait;
    use DescribeMultiplex\DescribeMultiplexTrait;
    use DescribeMultiplexProgram\DescribeMultiplexProgramTrait;
    use DescribeOffering\DescribeOfferingTrait;
    use DescribeReservation\DescribeReservationTrait;
    use DescribeSchedule\DescribeScheduleTrait;
    use DescribeAccountConfiguration\DescribeAccountConfigurationTrait;
    use DescribeThumbnails\DescribeThumbnailsTrait;
    use ListChannels\ListChannelsTrait;
    use ListInputDeviceTransfers\ListInputDeviceTransfersTrait;
    use ListInputDevices\ListInputDevicesTrait;
    use ListInputSecurityGroups\ListInputSecurityGroupsTrait;
    use ListInputs\ListInputsTrait;
    use ListMultiplexPrograms\ListMultiplexProgramsTrait;
    use ListMultiplexes\ListMultiplexesTrait;
    use ListOfferings\ListOfferingsTrait;
    use ListReservations\ListReservationsTrait;
    use ListTagsForResource\ListTagsForResourceTrait;
    use PurchaseOffering\PurchaseOfferingTrait;
    use RebootInputDevice\RebootInputDeviceTrait;
    use RejectInputDeviceTransfer\RejectInputDeviceTransferTrait;
    use UpdateAccountConfiguration\UpdateAccountConfigurationTrait;
    use StartChannel\StartChannelTrait;
    use StartInputDeviceMaintenanceWindow\StartInputDeviceMaintenanceWindowTrait;
    use StartMultiplex\StartMultiplexTrait;
    use StopChannel\StopChannelTrait;
    use StopMultiplex\StopMultiplexTrait;
    use TransferInputDevice\TransferInputDeviceTrait;
    use UpdateChannel\UpdateChannelTrait;
    use UpdateChannelClass\UpdateChannelClassTrait;
    use UpdateInput\UpdateInputTrait;
    use UpdateInputDevice\UpdateInputDeviceTrait;
    use UpdateInputSecurityGroup\UpdateInputSecurityGroupTrait;
    use UpdateMultiplex\UpdateMultiplexTrait;
    use UpdateMultiplexProgram\UpdateMultiplexProgramTrait;
    use UpdateReservation\UpdateReservationTrait;
}
